/** DS160 form field definitions - all optional. Labels match DS-160 FORM FILLING document. */

export const DS160_SECTIONS = [
  { id: "reference", title: "REFERENCE CONSULTANT (Whose client is this?)" },
  { id: "personal1", title: "PERSONAL INFORMATION 1" },
  { id: "personal2", title: "PERSONAL INFORMATION 2" },
  { id: "travel", title: "TRAVEL INFORMATION" },
  { id: "travelCompanions", title: "TRAVEL COMPANIONS INFORMATION" },
  { id: "previousUSTravel", title: "PREVIOUS US TRAVEL INFORMATION" },
  { id: "address", title: "ADDRESS INFORMATION" },
  { id: "passport", title: "PASSPORT INFORMATION" },
  { id: "usContact", title: "US POINT OF CONTACT INFORMATION" },
  { id: "family", title: "FAMILY INFORMATION" },
  { id: "presentWork", title: "PRESENT WORK/EDUCATION/TRAINING" },
  { id: "previousWork", title: "PREVIOUS WORK INFORMATION" },
  { id: "academic", title: "ACADEMIC INFORMATION" },
  { id: "additional", title: "ADDITIONAL INFORMATION" },
  { id: "tempWork", title: "TEMPORARY WORK INFORMATION (FOR H1B VISA)" },
  { id: "i20", title: "I-20/DS 2019 INFORMATION (FOR F1/J1 CATEGORY)" },
] as const;

/** All DS160 fields: key -> label. All optional in form. */
export const DS160_FIELDS: Record<string, string> = {
  referenceConsultant: "REFERENCE CONSULTANT (Whose client is this?)",
  // Personal 1
  surnameAsInPassport: "SURNAME AS IN PASSPORT",
  givenNameAsInPassport: "GIVEN NAME AS IN PASSPORT",
  haveYouUsedOtherNames: "HAVE YOU EVER USED OTHER NAMES? (i.e, maiden, religious, professional, alias etc?)",
  sex: "SEX",
  dateOfBirth: "DATE OF BIRTH",
  maritalStatus: "MARITAL STATUS",
  placeOfBirth: "PLACE OF BIRTH",
  // Personal 2
  nationality: "NATIONALITY",
  otherNationality: "DO YOU HOLD OR HAVE YOU HELD A NATIONALITY OTHER THAN THE ONE YOU HAVE INDICATED ABOVE",
  nationalIdNumber: "NATIONAL IDENTIFICATION NUMBER",
  usSocialSecurityNumber: "US SOCIAL SECURITY NUMBER",
  usTaxpayerIdNumber: "US TAX PAYER ID NUMBER",
  // Travel
  principleApplicantCategory: "ARE YOU THE PRINCIPLE APPLICANT (CATEGORY: B1, B2, F1, J1)",
  purposeOfTripToUS: "PURPOSE OF TRIP TO THE US (BUSINESS OR TOURIST OR STUDY)",
  intendedDateOfArrival: "INTENDED DATE OF ARRIVAL",
  intendedLengthOfStay: "INTENDED LENGTH OF STAY",
  addressWhereYouWillStayInUS: "ADDRESS WHERE YOU WILL STAY IN US (STREET, CITY, STATE)",
  phoneNumber: "PHONE NUMBER",
  emailId: "E-MAIL ID",
  personPayingForTrip: "PERSON/ENTITY PAYING FOR YOUR TRIP (NAME, SURNAME, ADDRESS - STREET, CITY, STATE, COUNTRY)",
  relationshipToYou: "RELATIONSHIP TO YOU",
  // Travel companions
  otherPersonTravellingWithYou: "ARE THERE OTHER PERSON TRAVELLING WITH YOU (IF YES PLEASE PROVIDE THE BELOW)",
  companionSurname: "SURNAME",
  companionGivenName: "GIVEN NAME",
  companionRelationship: "RELATIONSHIP",
  travellingAsPartOfGroup: "ARE YOU TRAVELLING AS A PART OF A GROUP OR ORGANIZATION",
  // Previous US travel
  haveYouEverBeenInUS: "HAVE YOU EVER BEEN IN THE US? (IF YES PLEASE PROVIDE THE BELOW DETAILS)",
  visit1Date: "VISIT 1 - DATE (DD/MM/YYYY)",
  visit1LengthOfStay: "VISIT 1 - LENGTH OF STAY",
  visit2Date: "VISIT 2 - DATE",
  visit2LengthOfStay: "VISIT 2 - LENGTH OF STAY",
  visit3Date: "VISIT 3 - DATE",
  visit3LengthOfStay: "VISIT 3 - LENGTH OF STAY",
  visit4Date: "VISIT 4 - DATE",
  visit4LengthOfStay: "VISIT 4 - LENGTH OF STAY",
  visit5Date: "VISIT 5 - DATE",
  visit5LengthOfStay: "VISIT 5 - LENGTH OF STAY",
  haveYouBeenIssuedUSVisa: "HAVE YOU EVER BEEN ISSUED US VISA? (IF YES PLEASE PROVIDE THE BELOW DETAILS)",
  visaNumber: "VISA NUMBER (PRINTED IN RED COLOUR IN YOUR VISA)",
  dateOfVisaIssue: "DATE OF VISA ISSUE",
  typeOfVisa: "TYPE OF VISA",
  refusedWithdrawnUSVisa: "HAVE YOU EVER BEEN REFUSED/WITHDRAWN US VISA (IF YES, PLEASE PROVIDE THE REASON)",
  haveYouBeenTenPrinted: "HAVE YOU BEEN TEN PRINTED (NOT FOR FIRST TIME TRAVELLER)",
  // Address
  homeAddress: "HOME ADDRESS",
  mailingAddress: "MAILING ADDRESS",
  isMailingSameAsHome: "IS YOUR MAILING ADDRESS SAME AS YOUR HOME ADDRESS",
  homeTelephoneNumber: "HOME TELEPHONE NUMBER",
  workPhoneNumber: "WORK PHONE NUMBER",
  workFaxNumber: "WORK FAX NUMBER",
  mobileNumber: "MOBILE NUMBER",
  emailAddress: "EMAIL ADDRESS",
  facebookId: "FACEBOOK ID",
  twitterId: "TWITTER ID",
  // Passport
  passportNumber: "PASSPORT NUMBER",
  countryAuthorityIssuedPassport: "COUNTRY/AUTHORITY THAT ISSUED PASSPORT",
  passportIssuedCity: "WHERE WAS THE PASSPORT ISSUED - CITY",
  passportIssuedState: "WHERE WAS THE PASSPORT ISSUED - STATE",
  passportIssuedCountry: "WHERE WAS THE PASSPORT ISSUED - COUNTRY",
  dateOfIssue: "DATE OF ISSUE",
  dateOfExpiry: "DATE OF EXPIRY",
  haveYouEverLostPassport: "HAVE YOU EVER LOST A PASSPORT OR HAD STOLEN",
  // US point of contact
  contactPersonSurnameGivenName: "CONTACT PERSON SURNAME AND GIVEN NAME",
  organizationName: "ORGANIZATION NAME",
  relationshipToYouContact: "RELATIONSHIP TO YOU",
  addressOfPointOfContact: "ADDRESS OF THE POINT OF CONTACT",
  contactPhoneNumber: "PHONE NUMBER",
  contactEmailId: "EMAIL ID",
  // Family
  fatherSurname: "FATHER'S SURNAME",
  fatherGivenName: "FATHER'S GIVEN NAME",
  fatherDateOfBirth: "FATHER'S DATE OF BIRTH",
  isFatherInUS: "IS YOUR FATHER IN US",
  motherSurname: "MOTHER'S SURNAME",
  motherGivenName: "MOTHER'S GIVEN NAME",
  motherDateOfBirth: "MOTHER'S DATE OF BIRTH",
  isMotherInUS: "IS YOUR MOTHER IN US",
  immediateRelativesInUS: "DO YOU HAVE ANY IMMEDIATE RELATIVES IN US, NOT INCLUDING PARENTS? (LIKE SPOUSE, SIBLING)",
  relativeSurname: "SURNAME",
  relativeGivenName: "GIVEN NAME",
  immigrantStatus: "IMMIGRANT STATUS",
  spouseSurname: "SPOUSE SURNAME",
  spouseGivenName: "SPOUSE GIVEN NAME",
  spouseDateOfBirth: "SPOUSE'S DATE OF BIRTH",
  spouseNationality: "SPOUSE NATIONALITY",
  spousePlaceOfBirth: "SPOUSE PLACE OF BIRTH",
  spouseAddress: "SPOUSE ADDRESS",
  // Present work
  primaryOccupation: "PRIMARY OCCUPATION CHOOSE FROM THE ABOVE (e.g. AGRICULTURE, ARTIST, BUSINESS, STUDENT, OTHER)",
  presentEmployerName: "PRESENT EMPLOYER NAME",
  employerStreetAddress1: "EMPLOYER STREET ADDRESS (LINE 1)",
  employerStreetAddress2: "EMPLOYER STREET ADDRESS (LINE 2)",
  employerCity: "CITY",
  employerStateProvince: "STATE/PROVINCE",
  employerPostalCode: "POSTAL ZONE/ZIP CODE",
  employerCountry: "COUNTRY",
  employerTelephoneNumber: "TELEPHONE NUMBER",
  employerEmailId: "EMAIL ID",
  jobTitle: "JOB TITLE",
  employmentStartDate: "EMPLOYMENT START DATE",
  monthlySalary: "MONTHLY SALARY",
  brieflyDescribeDuties: "BRIEFLY DESCRIBE YOUR DUTIES",
  ifNotEmployedPreviouslyEmployed: "IF NOT EMPLOYED OR HOMEMAKER WERE YOU PREVIOUSLY EMPLOYED?",
  // Previous work
  wereYouPreviouslyEmployed: "WERE YOU PREVIOUSLY EMPLOYED?",
  previousEmployerName: "EMPLOYER NAME",
  previousEmployerAddress1: "EMPLOYER STREET ADDRESS (LINE 1)",
  previousEmployerAddress2: "EMPLOYER STREET ADDRESS (LINE 2)",
  previousEmployerCity: "CITY",
  previousEmployerState: "STATE/PROVINCE",
  previousEmployerPostalCode: "POSTAL ZONE/ZIP CODE",
  previousEmployerCountry: "COUNTRY",
  previousEmployerPhone: "TELEPHONE NUMBER",
  previousJobTitle: "JOB TITLE",
  supervisorSurname: "SUPERVISOR'S SURNAME",
  supervisorGivenName: "SUPERVISOR'S GIVEN NAME",
  employmentDateFrom: "EMPLOYMENT DATE FROM",
  employmentDateTo: "EMPLOYMENT DATE TO",
  previousDescribeDuties: "BRIEFLY DESCRIBE YOUR DUTIES",
  // Academic
  schoolCollegeLastStudied: "SCHOOL/COLLEGE LAST STUDIED WITH COMPLETE ADDRESS",
  periodOfStudy: "PERIOD OF STUDY (DD/MM/YYYY to DD/MM/YYYY)",
  courseLastStudied: "COURSE LAST STUDIED",
  otherDiplomaCourses: "ANY OTHER ADDITIONAL DIPLOMA COURSES ATTENDED IF SO PLEASE MENTION",
  // Additional
  travelledToCountriesLastFiveYears: "HAVE YOU TRAVELLED TO ANY COUNTRIES WITHIN THE LAST FIVE YEARS? IF YES, LIST THEM.",
  languagesYouSpeak: "LIST OF LANGUAGES YOU KNOW TO SPEAK",
  professionalSocialCharitableOrgs: "HAVE YOU BELONGED TO, CONTRIBUTED TO, OR WORKED FOR ANY PROFESSIONAL, SOCIAL, OR CHARITABLE ORGANIZATIONS? IF YES, PROVIDE NAMES",
  specializedSkillsTraining: "DO YOU HAVE ANY SPECIALIZED SKILLS OR TRAINING, INCLUDING FIREARMS, EXPLOSIVES, NUCLEAR, BIOLOGICAL, OR CHEMICAL EXPERIENCE?",
  // Temp work H1B
  whereDoYouIntendToWork: "WHERE DO YOU INTEND TO WORK",
  nameOfEmployer: "NAME OF THE EMPLOYER",
  usStreetAddress: "U S STREET ADDRESS",
  usCity: "CITY",
  usPincode: "PINCODE",
  usState: "STATE",
  monthlySalaryUSD: "ENTER MONTHLY SALARY (IN USD)",
  applicationReceiptPetitionNumber: "DO YOU HAVE AN APPLICATION RECEIPT/PETITION NUMBER (IF YES, PROVIDE BELOW DETAILS)",
  nameOfPersonCompanyWhoFiledPetition: "NAME OF PERSON/COMPANY WHO FILED PETITION",
  applicationReceiptNumber: "APPLICATION RECEIPT/PETITION NUMBER?",
  // I-20 / F1 J1
  additionalContact1Name: "ADDITIONAL POINT OF CONTACT 1 - NAME",
  additionalContact1Address: "ADDRESS",
  additionalContact1City: "CITY",
  additionalContact1State: "STATE",
  additionalContact1Telephone: "TELEPHONE NUMBER",
  additionalContact1Email: "EMAIL",
  additionalContact2Name: "ADDITIONAL POINT OF CONTACT 2 - NAME",
  additionalContact2Address: "ADDRESS",
  additionalContact2City: "CITY",
  additionalContact2State: "STATE",
  additionalContact2Telephone: "TELEPHONE NUMBER",
  additionalContact2Email: "EMAIL",
  sevisId: "SEVIS ID",
  doYouIntendToStudyInUS: "DO YOU INTEND TO STUDY IN US?",
  nameOfSchool: "NAME OF THE SCHOOL",
  courseOfStudy: "COURSE OF STUDY",
  streetAddressSchool: "STREET ADDRESS",
};

/** Map section id to field keys for grouping form */
export const DS160_FIELDS_BY_SECTION: Record<string, string[]> = {
  reference: ["referenceConsultant"],
  personal1: ["surnameAsInPassport", "givenNameAsInPassport", "haveYouUsedOtherNames", "sex", "dateOfBirth", "maritalStatus", "placeOfBirth"],
  personal2: ["nationality", "otherNationality", "nationalIdNumber", "usSocialSecurityNumber", "usTaxpayerIdNumber"],
  travel: ["principleApplicantCategory", "purposeOfTripToUS", "intendedDateOfArrival", "intendedLengthOfStay", "addressWhereYouWillStayInUS", "phoneNumber", "emailId", "personPayingForTrip", "relationshipToYou"],
  travelCompanions: ["otherPersonTravellingWithYou", "companionSurname", "companionGivenName", "companionRelationship", "travellingAsPartOfGroup"],
  previousUSTravel: ["haveYouEverBeenInUS", "visit1Date", "visit1LengthOfStay", "visit2Date", "visit2LengthOfStay", "visit3Date", "visit3LengthOfStay", "visit4Date", "visit4LengthOfStay", "visit5Date", "visit5LengthOfStay", "haveYouBeenIssuedUSVisa", "visaNumber", "dateOfVisaIssue", "typeOfVisa", "refusedWithdrawnUSVisa", "haveYouBeenTenPrinted"],
  address: ["homeAddress", "mailingAddress", "isMailingSameAsHome", "homeTelephoneNumber", "workPhoneNumber", "workFaxNumber", "mobileNumber", "emailAddress", "facebookId", "twitterId"],
  passport: ["passportNumber", "countryAuthorityIssuedPassport", "passportIssuedCity", "passportIssuedState", "passportIssuedCountry", "dateOfIssue", "dateOfExpiry", "haveYouEverLostPassport"],
  usContact: ["contactPersonSurnameGivenName", "organizationName", "relationshipToYouContact", "addressOfPointOfContact", "contactPhoneNumber", "contactEmailId"],
  family: ["fatherSurname", "fatherGivenName", "fatherDateOfBirth", "isFatherInUS", "motherSurname", "motherGivenName", "motherDateOfBirth", "isMotherInUS", "immediateRelativesInUS", "relativeSurname", "relativeGivenName", "immigrantStatus", "spouseSurname", "spouseGivenName", "spouseDateOfBirth", "spouseNationality", "spousePlaceOfBirth", "spouseAddress"],
  presentWork: ["primaryOccupation", "presentEmployerName", "employerStreetAddress1", "employerStreetAddress2", "employerCity", "employerStateProvince", "employerPostalCode", "employerCountry", "employerTelephoneNumber", "employerEmailId", "jobTitle", "employmentStartDate", "monthlySalary", "brieflyDescribeDuties", "ifNotEmployedPreviouslyEmployed"],
  previousWork: ["wereYouPreviouslyEmployed", "previousEmployerName", "previousEmployerAddress1", "previousEmployerAddress2", "previousEmployerCity", "previousEmployerState", "previousEmployerPostalCode", "previousEmployerCountry", "previousEmployerPhone", "previousJobTitle", "supervisorSurname", "supervisorGivenName", "employmentDateFrom", "employmentDateTo", "previousDescribeDuties"],
  academic: ["schoolCollegeLastStudied", "periodOfStudy", "courseLastStudied", "otherDiplomaCourses"],
  additional: ["travelledToCountriesLastFiveYears", "languagesYouSpeak", "professionalSocialCharitableOrgs", "specializedSkillsTraining"],
  tempWork: ["whereDoYouIntendToWork", "nameOfEmployer", "usStreetAddress", "usCity", "usPincode", "usState", "monthlySalaryUSD", "applicationReceiptPetitionNumber", "nameOfPersonCompanyWhoFiledPetition", "applicationReceiptNumber"],
  i20: ["additionalContact1Name", "additionalContact1Address", "additionalContact1City", "additionalContact1State", "additionalContact1Telephone", "additionalContact1Email", "additionalContact2Name", "additionalContact2Address", "additionalContact2City", "additionalContact2State", "additionalContact2Telephone", "additionalContact2Email", "sevisId", "doYouIntendToStudyInUS", "nameOfSchool", "courseOfStudy", "streetAddressSchool"],
};
